name = "jluong/quorum"
version = "0.0.0"
compiler = "v1.1.22"
plutus = "v3"
license = "Apache-2.0"
description = "Quorum — on-chain governance protocol for Cardano"

[repository]
user = "jluong"
project = "Quorum_ADA"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.1.0"
source = "github"

[config]
